creativeselector/urls.py
from django.conf.urls.defaults import *

django_facebook/urls.py
from django.conf.urls.defaults import patterns, url, include


urlpatterns = patterns('django_facebook.views',
   url(r'^connect/$', 'connect', name='facebook_connect'),
   url(r'^register/$', 'register_user', name='register_user'),
)


mediagenerator/urls.py
from .settings import MEDIA_DEV_MODE
from django.conf import settings
from django.conf.urls.defaults import *
import re

urlpatterns = patterns('')

if MEDIA_DEV_MODE:
    urlpatterns += patterns('',
        (r'^%s(?P<filename>.+)$'
            % re.escape(settings.MEDIA_URL.lstrip('/')),
         'mediagenerator.views.serve_dev_mode'),
    )

urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from django.contrib import admin
from django.contrib.sitemaps import GenericSitemap
from creativeselector.models import *
from django.contrib.sitemaps import Sitemap
import settings
import creativeselector



#############################
# SITEMAPS
#############################
class StaticPagesSitemap(Sitemap): 
    changefreq = "yearly" 
    priority = 0.5 
    def items(self): 
      return ['/',
              '/miez',
              '/rolunk',
              '/faq',
              '/feltetelek',
              '/adatkezeles',
              '/kapcsolat',
              ] 
    def location(self, obj): 
      return obj

sitemaps = {
#    'mentors': GenericSitemap({'queryset': Mentor.objects.all(),}, priority=0.6,  changefreq='never'),
    'blogs': GenericSitemap({'queryset': BlogEntry.objects.all(), 'date_field': 'created',}, priority=0.6,  changefreq='hourly'),
    'tenders': GenericSitemap({'queryset': Tender.objects.all(), 'date_field': 'created',}, priority=0.6,  changefreq='hourly'),
    'statics': StaticPagesSitemap,
}

#############################
# ADMIN URLS
#############################
admin.autodiscover()

urlpatterns = patterns('',
  (r'^admin/', include(admin.site.urls)),
)

#############################
# SITEMAP URLS
#############################
urlpatterns += patterns('',
  (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
)

#############################
# FACEBOOK URLS
#############################
urlpatterns += patterns('',
    (r'^facebook/', include('django_facebook.urls')),
)

#############################
# VIEW URLS
#############################

if settings.MEDIA_DEV_MODE:
    # Generate media on-the-fly
    from mediagenerator.urls import urlpatterns as mediaurls
    urlpatterns += mediaurls


urlpatterns += patterns('creativeselector.views',
  (r'^upload/', include('adminupload.urls')),
  (r'^$', 'index'),
  (r'^import_rss$', 'import_rss'),
  (r'^switch_lang$', 'to_english'),
  (r'^projekts_are_late$', 'end_projekts'),
  (r'^unfinished_projs_email$', 'unfinished_projects'),
  #(r'^remove_tenders$', 'remove_tenders'),
  (r'^projekt_bekuldes$', 'send_project'),
  (r'^projektbekuldes2$', 'send_project2'),
  (r'^projektbekuldes3$', 'send_project3'),
  (r'^projekt_folyt/(.+)$', 'project_continue'),
  (r'^projekt_szerk/(.+)$', 'continue_project'),
  (r'^projekt_szerk2/(.+)$', 'continue_project2'),
  (r'^projekt_szerk3/(.+)$', 'continue_project2_2'),
  (r'^projekt_szerk4/(.+)$', 'continue_project3'),
  (r'^projekt_szerk5/(.+)$', 'continue_project4'),
  (r'^projekt_szerk6/(.+)$', 'continue_project5'),
  (r'^projekt_mentes/(.+)/(.+)$', 'saveproject'),
  (r'^projekt/show/(.+)$', 'get_project'),
  (r'^projekt/update/(.+)$', 'get_project_update'),
  (r'^projekt_aktivalas/(.+)$', 'projectpublic'),
  (r'^projekt_kiemeles/(.+)$', 'projecttomost'),
  (r'^projekt/supporters/(.+)$', 'projekt_supporters'),
  (r'^projekt/support/(.+)$', 'present_form'),
  (r'^pay/(.+)$', 'send_money'),
  (r'^pay2/(.+)/$', 'send_money2'),
  (r'^delete_trans/(.+)/(.+)/$', 'erase_transaction'),
  (r'^activate_proj/(.+)$', 'validate_project'),
  (r'^activate_proj_ok/(.+)$', 'validate_project_ok'),
  (r'^activate_proj_no/(.+)$', 'validate_project_no'),
  #(r'^reszletes_kiiras$', 'detailed_tender'),
  (r'^egyblog/(.+)$', 'blogentry'),
  #(r'^blogcomment/(.+)$', 'comment_show'),
  (r'^blogcommentdel/(.+)$', 'comment_del'),
  (r'^ideaorder/(.+)$', 'ideaorder'),
  (r'^blog/tag/(.+)$', 'blog_tag'),
  (r'^blog/oldal/(\d+)$', 'blog'),
  #(r'^remove_idea/(.+)$', 'remove_idea'),
  (r'^excel_export$', 'excel_export'),
  #(r'^excel_export_new$', 'excel_export_new'),
  #(r'^ideauser_get$', 'ideauser_get'),
  (r'^users/get/them/all/$', 'user_get'),
  #(r'^test_mail_send$', 'test_mail_send'),
  #(r'^gallery$', 'gallery'),
  (r'^comments/blog/list/$', 'list_all_comments'),
  (r'^proj/admin/list/$', 'admin_projs'),
  (r'^endproj/admin/list/$', 'admin_end_projs'),
  (r'^sups/admin/list/$', 'admin_sups'),
  (r'^budget/admin/list/$', 'admin_budget'),
  (r'^most/admin/list/$', 'mosttender_admin'),
  (r'^new_proj/admin/list/$', 'admin_new_proj'),
  (r'^names/admin/list/$', 'admin_names'),
  (r'^names/admin/to_ex/$', 'names_to_excel'),
  (r'^proj/admin/(.+)$', 'admin_list_proj'),
  (r'^user_reg$', 'userreg'),
  (r'^activate/(.+)$', 'activate_user'),
  (r'^forget_pass/(.+)$', 'forget_pass'),
  (r'^user_profil/(.+)$', 'get_user_profile'),
  (r'^own_projekt/(.+)$', 'owner_project'),
  (r'^user_log$', 'user_login'),
  (r'^unsubscribe$', 'unsubscribe'),
  (r'^main_pass$', 'passed_page'),
  (r'^user_log_out$', 'user_logout'),
  (r'^delete_user$', 'deluser'),
  (r'^delete_user_final$', 'deleteuser'),
  #(r'^osszes$', 'all_ideas'),
  (r'^export_users_batch/(\d+)/(\d+)/(\d+)$', 'export_users_batch'),
  
  (r'^export_users$', 'export_users'),
  (r'^ideasbytag/(.+)$', 'ideasbytag'),
  (r'^projektek/kiemelt/kat/(.+)$', 'ideasbymost'),
  (r'^projektek/kat/fin/(.+)$', 'ideasbyfin'),
  (r'^projektek/kat/success/(.+)$', 'ideasbyfin'),
  (r'^projektek/kat/(.+)$', 'ideasbyfresh'),
  (r'^projektek$', 'ideas'),
  (r'^frissprojektek$', 'ideasbyfresh'),
  (r'^finishprojektek$', 'ideasbyfin'),
  (r'^endprojektek$', 'ideasbyend'),
  (r'^sikeresprojektek$', 'ideasbysucces'),
  (r'^projektek/kiemelt/(.+)/(.+)/kat/(.+)$', 'mostideas'),
  (r'^projektek/kiemelt/(.+)/(.+)$', 'mostideas'),
  (r'^projektek/friss/(.+)/(.+)/kat/(.+)$', 'freshideas'),
  (r'^projektek/friss/(.+)/(.+)$', 'freshideas'),
  (r'^projektek/finish/(.+)/(.+)/kat/(.+)$', 'finideas'),
  (r'^projektek/finish/(.+)/(.+)$', 'finideas'),
  (r'^projektek/end/(.+)/(.+)/kat/(.+)$', 'endideas'),
  (r'^projektek/end/(.+)/(.+)$', 'endideas'),
  (r'^projektek/success/(.+)/(.+)/kat/(.+)$', 'succesideas'),
  (r'^projektek/success/(.+)/(.+)$', 'succesideas'),
    
  (r'^refresh_related_items$', 'refresh_related_items'),
  (r'^refresh_one_related_item/(.+)$', 'refresh_one_related_item'),
  
  
  (r'^export_users_task/(\d+)$', 'export_users_task'),
  #(r'^otlet_bekuldese/(.+)$', 'send_idea'),
  #(r'^otlet_bekuldese$', 'send_idea'),
  #(r'^support_idea$', 'support_idea'),
  #(r'^fajl_feltoltese/(.+)$', 'send_idea2'),
  (r'^profilom$', 'profile'),
  #(r'^avatar_torles$', 'delete_user_photo'),
  #(r'^flush_memcache$', 'flush_memcache'),
  (r'^remove/tenderimage/(.+)$', 'remove_tenderimage'),
  #(r'^update_users$', 'update_users'),
  #(r'^otlet/(.+)$', 'ideaentry'),

  #(r'^necc/list/(.+)$', 'necc_category'),
  #(r'^necc/list$', 'necc_category_all'),
  #(r'^necc/search/(.+)$', 'necc_search'),
  
  (r'^tagging_autocomplete/', include('tagging_autocomplete.urls')),

  #(r'^setsupport$', 'setsupport'),
  (r'^(.+)$', 'render_direct'),
)

creativeselector/models.py
# -*- coding: utf-8 -*-
import datetime
import urllib
import logging
from django.contrib.auth.models import User, UserManager
from django.db import models
from django.utils.encoding import smart_str
from django.utils.hashcompat import md5_constructor, sha_constructor
from django.utils.translation import ugettext_lazy as _
from creativeselector.util import send_mail, slugify
from django.db.models import permalink
from django.contrib.sitemaps import ping_google
from django.db.models import Max
import random
from django.db import models
from django.conf import settings



#################################################
# HELPER METHOS
#################################################

UNUSABLE_PASSWORD = '!' # This will never be a valid hash

def get_hexdigest(algorithm, salt, raw_password):
    """
    Returns a string of the hexdigest of the given plaintext password and salt
    using the given algorithm ('md5', 'sha1' or 'crypt').
    """
    raw_password, salt = smart_str(raw_password), smart_str(salt)
    if algorithm == 'crypt':
        try:
            import crypt
        except ImportError:
            raise ValueError('"crypt" password algorithm not supported in this environment')
        return crypt.crypt(raw_password, salt)

    if algorithm == 'md5':
        return md5_constructor(salt + raw_password).hexdigest()
    elif algorithm == 'sha1':
        return sha_constructor(salt + raw_password).hexdigest()
    raise ValueError("Got unknown password algorithm type in password.")

def check_password(raw_password, enc_password):
    """
    Returns a boolean of whether the raw_password was correct. Handles
    encryption formats behind the scenes.
    """
    algo, salt, hsh = enc_password.split('$')
    #logging.error("PASSS CHECK: %s = %s" % (hsh, get_hexdigest(algo, salt, raw_password)))
    return hsh == get_hexdigest(algo, salt, raw_password)

def sitemap_ping():
    try:
        pass
        #ping_google()
    except Exception:
        # Bare 'except' because we could get a variety
        # of HTTP-related exceptions.
        pass


#################################################
# PROX MODELS TO SEPARATE IN THE ADMIN THE USER MODELS
#################################################

class Staff(User):
    class Meta:
        proxy = True
        app_label = 'auth'
        verbose_name = 'Staff account'
        verbose_name_plural = 'Staff accounts'

  
class SiteMeta(models.Model):
    link = models.CharField("link", max_length=200)
    title = models.CharField("Title", max_length=200)
    keywords = models.TextField("Keywords", max_length=1000)
    description = models.TextField("Description", max_length=1000)

    def __unicode__(self):
       return u"%s - %s" % (self.link, self.title)

    class Meta:
      verbose_name = 'Meta adat'
      verbose_name_plural = 'Meta adatok'


#######################################################################
# BLOG       
#######################################################################
from tagging.fields import TagField
from tagging.models import Tag

class BlogEntry(models.Model):
    title = models.CharField("Title", max_length=200)
    link = models.CharField("Link2", max_length=200, blank = True)
    tagss = TagField("Tags")
    content = models.TextField("Content", max_length=1000)
    created = models.DateTimeField(_('created'), default=datetime.datetime.now)
    published = models.BooleanField(_('Published'), default=False)

    def __unicode__(self):
        return self.title 
    
    def _get_tags(self):
        return Tag.objects.get_for_object(self)

    def _set_tags(self, tag_list):
        Tag.objects.update_tags(self, tag_list)

    tags = property(_get_tags, _set_tags)

    def generate_tags(self):
        self.tagss = generate_tags_blog(u"%s" % (self.title))
        super(BlogEntry, self).save()

    def tag_splited(self):
        txt=u"%s" % (self.tagss)
        words=txt.split(" ")
        return words

    @models.permalink
    def get_absolute_url(self):
        return ('creativeselector.views.blogentry', [str(self.link)])

    def save(self, *args, **kwargs):
        if not self.link:
          self.link = slugify(u"%s_%s" %  (self.title, self.created))
        if not self.tagss:
          self.generate_tags()
        super(BlogEntry, self).save(*args, **kwargs)
        sitemap_ping()       

    class Meta:
       verbose_name = 'Blog bejegyzés'
       verbose_name_plural = 'Blog bejegyzések'


class BlogComment(models.Model):
    blog = models.ForeignKey(BlogEntry)
    user = models.ForeignKey(User)
    comment = models.TextField("Comment", max_length=1000)
    slug = models.CharField("Link", max_length=200, blank = True)
    created = models.DateTimeField("Létrehozva", default=datetime.datetime.now)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(u"%s_%s" %  (self.blog.link, self.created))
        super(BlogComment, self).save(*args, **kwargs)

    class Meta:
       verbose_name = 'Blog komment'
       verbose_name_plural = 'Blog kommentek'
       ordering = ('created',)

def generate_tags_blog(string):
  

  # remove all separator
  string = re.sub(tag_strip_pattern, ' ', string).lower()
  
  # get all words
  words = string.split(" ")

  
  # unify
  words_set = set(words)
  
  
  # empty result
  result = []
  
  # iterate over all words
  for word in words_set:
    if len(word) > 3 and not word.isdigit():
        result.append(word)
  
  result = set(result)
  resultString =  " ".join(result)
  resultString =  resultString[:499]
  
  return resultString

#######################################################################
# STATIC PAGES       
#######################################################################
class Staticpage(models.Model):
   title = models.CharField("Title", max_length=200)
   link = models.CharField("Link", max_length=200, blank = True)
   content = models.TextField("Content", max_length=1000)
   
   def __unicode__(self):
       return self.title 

   @permalink
   def get_absolute_url(self):
       return ('creativeselector.views.staticpage', (),
              { 
              'slug': '%s' % self.link
              }
              )

   def save(self, *args, **kwargs):
       if not self.link:
         self.link = slugify(u"%s" % self.title)
       super(Staticpage, self).save(*args, **kwargs)
       sitemap_ping()
       
   class Meta:
      verbose_name = 'Statikus oldal'
      verbose_name_plural = 'Statikus oldalak'       
       
class BlackWords(models.Model):
    word = models.CharField("Szó", max_length=200)

    def __unicode__(self):
       return self.word

    def save(self, *args, **kwargs):
       super(BlackWords, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Tiltott szó'
        verbose_name_plural = 'Tiltott szavak'
       

#######################################################################
# Tender       
#######################################################################
import logging
import re
tag_strip_pattern = re.compile(r'[\W]+', re.UNICODE)

def check_word_in_whitelist(whitelist, word):
  for item in whitelist:
    item = u"%s" % item
    word = u"%s" % word
    if word in item or item in word:
      return item
  return None
  


def generate_tags_helper(string):
  # get black list
  whiteStatic = Staticpage.objects.get(link = "feher_lista")

  whitelist = re.sub(tag_strip_pattern, ' ', whiteStatic.content).lower()
  whitelist = set(whitelist.split(" "))

  # remove all separator
  string = re.sub(tag_strip_pattern, ' ', string).lower()
  
  # get all words
  words = string.split(" ")

  
  # unify
  words_set = set(words)
  
  
  # empty result
  result = []
  
  # iterate over all words
  for word in words_set:
    if len(word) > 3 and not word.isdigit():
      inlist = check_word_in_whitelist(whitelist, word)
      if inlist:
        result.append(inlist)
  
  result = set(result)
  resultString =  " ".join(result)
  resultString =  resultString[:499]
  
  return resultString
  
#######################################################################
# EXAMPLES      
#######################################################################
class Example(models.Model):
   title = models.CharField("Title", max_length=200)
   link = models.CharField("Link", max_length=200, blank = True)
   content = models.TextField("Content", max_length=1000)
   website = models.CharField("Weboldal", max_length=200, blank = True)
   image = models.FileField("Kép", upload_to='uploads/%Y/%m/%d/%H/%M/%S/', blank = True, null = True)
   order = models.IntegerField("Sorrend", blank=True, default=0)
   
   def __unicode__(self):
       return self.title 

   def save(self, *args, **kwargs):
       if not self.link:
         self.link = slugify(u"%s" % self.title)
       super(Example, self).save(*args, **kwargs)
       sitemap_ping()

   class Meta:
      verbose_name = 'Példa'
      verbose_name_plural = 'Példák'       

# USER PROFILE
class UserNoFaceProfile(models.Model):
  user = models.OneToOneField(User, related_name="facebook_profile")

  password = models.CharField(u"jelszó*", max_length = 1000)
  password2 = models.CharField(u"jelszó*", max_length = 1000)
  mail = models.CharField("e-mail", max_length=200)
  first_name = models.CharField("Kereszt Név", max_length=200)
  last_name = models.CharField("Vezeték Név", max_length=200)
  image = models.FileField("Kép", upload_to='uploads/%Y/%m/%d/%H/%M/%S/', blank = True, null = True)  
  profile_link = models.CharField("Profil link", max_length=1000, blank=True, null=True)
    

  def __unicode__(self):
    return "%s %s" % (self.last_name, self.first_name)

  def save(self, new=True,*args, **kwargs):
      if self.password:
          if new:
              random.seed(self.pk)
              serial = random.randrange(0, 100000, 3)
              usr=User(username = "%s_%s_%s" % (self.last_name, self.first_name, serial),

creativeselector/templates/projekt/owner_proj_list.html
{% extends "simplecontent.html" %}
{% load replace video call %}

{% block content %}


  {% block content_top %}
  {% endblock %}

<div id="center_title" class="cufon">{% block content_tab %}Támogatóim{% endblock %}</div>
  <div id="content2"> 
      
    {% block content_text %}
	<script src="/media/js/nicEdit.js" type="text/javascript"></script>
	<script type="text/javascript" charset="utf-8">
		$(document).ready(function () {$('#id_content').val(''); $('.nicEdit-main').html(''); });
	 function validate(form_id) {
		 resetForm(form_id);
		 var valami=$('.nicEdit-main').html();
		 $('#id_content').val(valami);
		 $(f(form_id)).submit();
  
  }
  
bkLib.onDomLoaded(function(){ var myInstance = new nicEditor().panelInstance('id_content');});
</script>
<style type="text/css" charset="utf-8">
		 <!--
		 #id_content{
			width:580px;
			height:300px;
		 }
		 td{padding-top:10px; max-width:160px;}
		 table, tr, td {word-wrap: break-word;}
		-->
		</style> 
	<div id="owner_proj">
	<a href="{% url creativeselector.views.get_project proj.link %}"style="float:right">Projekt nyílvános elérhetősége</a>
	<p class="cufon" >{{proj.short_title}} </p>
	<span style="font-weight:normal;float:right;"><a href="#send_update_form" style="color:#dd0000;">Új frissítés írása</a></span>
	<p>Összes támogató</p>
	<table width="640">
		<tr><th style="text-align:left;" class="cufon">Név</th><th style="text-align:left;" class="cufon">Támogatás</th><th style="text-align:left;" class="cufon">e-mail</th><th style="text-align:left;" class="cufon">Postai cím</th></tr>
		{% for sup in supps %}
		
		
		<tr>			
			<td>{% ifequal sup.visibility 3 %}{% if sup.name %}{{sup.name}}{% else %}{{sup.user.last_name}} {{sup.user.first_name}}{% endif %} (Anonymus){% else %}{% if sup.name %}{{sup.name}}{% else %}{{sup.user.last_name}} {{sup.user.first_name}}{% endif %}{% endifequal %}</td>
			<td>{% ifequal sup.visibility 1 %}{{sup.money}},-{% else %}<!--{{sup.money}},--->(Nem látható){% endifequal %}</td>			
			<td>{{sup.user.email}}</td>
			<td>{{sup.adress}}, {{sup.zipcode}}, {{sup.city}}</td>
		</tr>
		{% endfor %}
		</table>
		<hr>
		<p>Támogatók, akik ajándékot kértek </p>
		<table style="100%">
		<tr><th class="cufon">Elküldve</th><th class="cufon">Név</th><th class="cufon">Támogatás</th><th class="cufon">Ajándék</th><th class="cufon">e-mail</th><th class="cufon">Postai cím</th></tr>
		{% for cou, sup in supp_pres %}
		<script type="text/javascript" charset="utf-8">
		 $(document).ready(function() {
				addBubble('pres_{{sup.pres}}', '{{sup.pres.detail|safe}}')
			});
			
		</script>
		
		<tr>
			<td><input type="checkbox" id="sup_{{sup.trid}}" name="sp_{{forloop.counter}}" value="{{sup.trid}}" {% if sup.get_pres %} checked{% endif %}></td>
			<td>{% if sup.name %}{{sup.name}}{% else %}{{sup.user.last_name}} {{sup.user.first_name}}{% endif %}</td>
			<td>{{sup.money}},-</td>
			<td><label id="pres_{{sup.pres}}">{{cou}}</label></td>
			<td>{{sup.user.email}}</td>
			<td>{{sup.adress}}, {{sup.zipcode}}, {{sup.city}}</td>
		</tr>
		{% endfor %}
		</table>
		<hr>
		<span class="cufon"> Mit ígértem? <img src="/media/images/pres_box.png" width="30"> </span>
		<table style="border:1px solid; margin-left:35px; width:250px">
		<tr style="border:1px solid #000000;"><th style="border:1px solid;text-align:left;width:20px;">#</th><th style="border:1px solid #000000;text-align:left;">Ajándék</th></tr>
			{% for prs in presents %}
			<tr style="border:1px solid #000000;"><td style="border:1px solid #000000;width:20px;">{{forloop.counter}} </td><td style="border:1px solid #000000;"> {{prs.detail|safe}}</td></tr>
			{% endfor %}
		</table>
		
		<hr class="potty">
		<p class="cufon">Projektleírás frissítése</p>
		<span style="font-size:12px">A frissitéseid a projekt adatlapján kiemelve jelennek meg és minden támogatódnak e-mailben értesítést küldünk róla</span>
		<form id="send_update_form" name="send_update_form" method="post"  > 
		{{form.content}}
		<br/>
		<br/>
		{% call "widgets/button.html" with title="elküld" click="validate('send_update_form')" %}
		</form>
		{% if tdus %}
		<p>&nbsp;</p>
		<p id="update_title">Utolsó frissítésed</p>
			
			<div class="updates"><a href="{% url creativeselector.views.get_project_update proj.link %}" style="color:#F26522;" ><span style="font-weight:bold">{{tdus.created|date:"Y.m.d | H:i"}}</span> <br/>
			{{tdus.content|slice:":250"|striptags}}...
			</a>			
			</div>
		{% endif %}
	</div>
	    {% endblock %}
  </div>
  <div id="content_bottom">
    {% block content_bottom %}
		
		
    {% endblock %}
  </div>


{% endblock %}

creativeselector/templates/projekt/proj_activation.html
{% extends "base.html" %}
{% load replace video call %}
{% block content %}


  {% block content_top %}
  {% endblock %}

<div id="center_title" class="cufon">{% block content_tab %}Projekt Akitválás{% endblock %}</div>
  <div id="content2"> 
      
    {% block content_text %}
	
	<script type="text/javascript" charset="utf-8">
	 $(document).ready(function () {
	 var num1=$('#full_money').html();
	 $('#full_money').html(separateNum(num1));
	 });
    // Form validator
  function validate(form_id) {
   resetForm(form_id);

   var valid = is_empty(form_id, 'mail_text', true);
   if (valid) {
     $(f(form_id)).submit();
   }
  }
  

</script>
	
	<p>{{projekt.short_title|safe}}</p>
	<p><b>Projekt gazda:</b> {{projekt.owner.last_name}} {{projekt.owner.first_name}} </p>
	<p><b>Projekt gazda email:</b> <a href="mailto:{{projekt.owner.email}}"> {{projekt.owner.email}}</a> </p>
	<p><b>Miről szól:</b> <br/>
	{{projekt.introduce|safe}}</p>
	<p><b>Felajnálott Ajándékok:</b> <br/>
	{% if presents %}
	<ul>
	{% for present in presents %}
	<script type="text/javascript" charset="utf-8">
	 $(document).ready(function () {
		var num=$('#pres_sup_num_{{forloop.counter}}').html();
		$('#pres_sup_num_{{forloop.counter}}').html(separateNum(num));
		});
	 </script>
		<li id="pres_sup_num_{{forloop.counter}}">{{present.min_prize}} Ft</li>
		<li>{{present.detail|safe}}</li>
	{% endfor %}
	</ul>
	{% endif %}
	</p>
	{% if projekt.why_sup %}<p><b>Kampányaktivitás:</b> <br/>
	{{projekt.why_sup|safe}}</p>{% endif %}
	<p><b>Weboldal/elérhetőség:</b> <br/>
	{{projekt.faceurl|safe}}</p>
	<p><b>Közösség létszáma:</b> 
	{{projekt.crowd_no}} fő</p>
	<p><b>Összegyűjtendő összeg:</b> 
	<span id="full_money">{{projekt.full_money|safe}} Ft</span></p>
	<p><b>Kategória:</b> 
	{{projekt.category}}</p>
	<p><b>Telefon szám:</b> 
	{{projekt.tel_no|safe}}</p>
	{% if is_admin %}
	<p><b>E-mail magyarázó szöveg ha valami hibás a projektben:</b><br/>
	<form method="post" action="/activate_proj_no/{{projekt.pk}}" name="validateform" id="validateform">
	{{form.mail_text}}
	</form></p>
	<div style="float:left;">{% call "widgets/button.html" with title="Hibás#Projekt" click="validate('validateform')" %}</div>
    
	<div><a href="{% url creativeselector.views.validate_project_ok projekt.pk %}">{% call "widgets/button.html" with title="Mehet" %}</a></div>
	{% endif %}
	{% endblock %}
  </div>
  <div id="content_bottom">
    {% block content_bottom %}

    {% endblock %}
  </div>


{% endblock %}